name: Cafe Duke Notes
title: Cafe Duke Notes
author: Raghunandan.Seshadri
email: raghubs81@gmail.com
github_username: cafeduke
description: Duke notes. Happy learning!
markdown: kramdown
syntax_highlighter: rouge

kramdown:
   parse_block_html: true

plugins:
   - jemoji
